name: Ruby Bindings

on:
  push:

jobs:
  ci-data:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.fetch.outputs.result }}
    steps:
      - uses: oxidize-rb/actions/fetch-ci-data@v1
        id: fetch
        # with:
        # supported-ruby-platforms: |
        #   exclude: [arm-linux]
        # stable-ruby-versions: |
        #   exclude: [head]
  cross-gem:
    name: Compile native gem for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    needs: ci-data
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.ci-data.outputs.result).supported-ruby-platforms }}
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - uses: oxidize-rb/actions/cross-gem@v1
        id: cross-gem
        with:
          working-directory: ./bindings/ruby
          platform: ${{ matrix.platform }}
          ruby-versions: ${{ join(fromJSON(needs.ci-data.outputs.result).stable-ruby-versions, ',') }}

      - uses: actions/upload-artifact@v4
        with:
          name: cross-gem-${{ matrix.platform }}
          path: ${{ steps.cross-gem.outputs.gem-path }}

  # release:
  #   needs: cross-gem
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: "3.1"
  #     - uses: actions/download-artifact@v4
  #       with:
  #         path: artifacts
  #     - name: Move gems to pkg directory
  #       run: |
  #         mkdir -p pkg
  #         find artifacts -name "*.gem" -exec mv {} pkg/ \;
  #     - name: Publish to RubyGems
  #       run: |
  #         mkdir -p ~/.gem
  #         echo -e "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
  #         chmod 0600 ~/.gem/credentials
  #         gem push pkg/*.gem
  #       env:
  #         RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
